services:
  init-db:
    image: python:3.9-slim
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend:/app
    networks:
      - shared_network
    entrypoint: ["/bin/bash", "-c", "pip install --no-cache-dir -r /app/init-db-requirements.txt && python /app/init_db.py"]

networks:
  shared_network:
    external: true
