version: '3.8'

networks:
  internal_network:
    driver: bridge

services:
  app:
    networks:
      - internal_network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./easyocr_models:/root/.EasyOCR/model
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh", "db", "python", "app.py"]

  db:
    image: postgres:13
    networks:
      - internal_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: