services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./migrations:/app/migrations  # Mount the migrations directory
      - ./logs:/app/logs  # Optional: persist logs
    env_file:
      - .env
    networks:
      - shared_network
    entrypoint: ["python", "app.py"]

networks:
  shared_network:
    external: true
