services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - .env
    networks:
      - shared_network
    entrypoint: ["python", "app.py"]

networks:
  shared_network:
    external: true
