"""Update credit amount to be decimal with 2 digits precision

Revision ID: 22d6c5982713
Revises: 8854e4b4e1ac
Create Date: 2025-01-04 11:50:13.499453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d6c5982713'
down_revision = '8854e4b4e1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_credit', schema=None) as batch_op:
        batch_op.alter_column('credit_count',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('personal_credit', schema=None) as batch_op:
        batch_op.alter_column('credit_count',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_credit', schema=None) as batch_op:
        batch_op.alter_column('credit_count',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('business_credit', schema=None) as batch_op:
        batch_op.alter_column('credit_count',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
