"""Add unique constraint to company_id in business_credit

Revision ID: 425758df25ce
Revises: 2700fcaedab5
Create Date: 2025-01-17 16:55:48.219030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425758df25ce'
down_revision = '2700fcaedab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_credit', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['company_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_credit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
