"""Add credit table and update models

Revision ID: 5cca3e2eee8f
Revises: 
Create Date: 2024-12-31 16:24:01.742365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cca3e2eee8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('credit_count')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('special_admin')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_count', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
