"""Add soft delete columns to User and Company models

Revision ID: 8854e4b4e1ac
Revises: 1333a1dcf854
Create Date: 2025-01-03 10:32:11.027300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8854e4b4e1ac'
down_revision = '1333a1dcf854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        # Add with default value and nullable=True temporarily
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        # Modify to set nullable=False after ensuring existing rows are updated
        batch_op.alter_column('is_deleted', nullable=False, server_default=None)

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add with default value and nullable=True temporarily
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        # Modify to set nullable=False after ensuring existing rows are updated
        batch_op.alter_column('is_deleted', nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
